// Command devsetup prepares a developer's machine to run the platform
// locally. Everything it produces is for local development only.
//
//	devsetup init                    write certificates, keys and .dev/local.env
//	devsetup topics                  create the Kafka topics
//	devsetup fund <customer> <kobo>  credit a customer's deposit account from the
//	                                 development funding account
//
// It refuses to run unless APP_ENV is local or test.
package main

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"

	commonv1 "bankplatform.internal/gen/bank/common/v1"
	ledgerv1 "bankplatform.internal/gen/bank/ledger/v1"
	"bankplatform.internal/platform/authn"
	"bankplatform.internal/platform/config"
	"bankplatform.internal/platform/devcert"
	"bankplatform.internal/platform/grpcx"
	"bankplatform.internal/platform/kafkax"
	"bankplatform.internal/services/ledger/contract"
	"bankplatform.internal/services/lending/app"
)

const dir = ".dev"

func main() {
	l := config.FromMap(map[string]string{"APP_ENV": envOr("APP_ENV", "local")})
	if env := l.Environment(); l.Err() != nil || !env.AllowsSimulators() {
		fail(fmt.Errorf("devsetup is refused unless APP_ENV is local or test"))
	}
	if len(os.Args) < 2 {
		fail(fmt.Errorf("usage: devsetup init | topics | fund <customer_id> <amount_minor>"))
	}
	var err error
	switch os.Args[1] {
	case "init":
		err = initDev()
	case "topics":
		err = topics()
	case "fund":
		if len(os.Args) != 4 {
			fail(fmt.Errorf("usage: devsetup fund <customer_id> <amount_minor>"))
		}
		err = fund(os.Args[2], os.Args[3])
	default:
		err = fmt.Errorf("unknown command %q", os.Args[1])
	}
	if err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "devsetup:", err)
	os.Exit(1)
}

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func randomKey() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(b), nil
}

func initDev() error {
	ca, err := devcert.NewAuthority()
	if err != nil {
		return err
	}
	leaves := map[string]*devcert.Leaf{}
	for _, svc := range []string{"ledger", "identity", "lending", "devtools"} {
		leaf, err := ca.Issue(grpcx.WorkloadURI(svc), "localhost", svc)
		if err != nil {
			return err
		}
		leaves[svc] = leaf
	}
	certs := filepath.Join(dir, "certs")
	if err := ca.WriteFiles(certs, leaves); err != nil {
		return err
	}

	_, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return err
	}
	privPEM, pubPEM, err := authn.EncodeKeyPair(priv)
	if err != nil {
		return err
	}
	keys := filepath.Join(dir, "keys")
	if err := os.MkdirAll(keys, 0o700); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(keys, "token-signing.pem"), privPEM, 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(keys, "token-public.pem"), pubPEM, 0o644); err != nil {
		return err
	}

	hmacKey, err := randomKey()
	if err != nil {
		return err
	}
	encKey, err := randomKey()
	if err != nil {
		return err
	}
	abs, err := filepath.Abs(dir)
	if err != nil {
		return err
	}
	pg := "postgres://%s:devpassword@localhost:55432/%s?sslmode=disable"
	env := []string{
		"# Generated by `make dev-setup`. Local development only; never commit.",
		"APP_ENV=local",
		"KAFKA_BROKERS=localhost:59092",
		"TLS_CA_FILE=" + filepath.Join(abs, "certs", "ca.pem"),
		"",
		"LEDGER_DATABASE_URL=" + fmt.Sprintf(pg, "ledger_app", "ledger"),
		"LEDGER_OWNER_DATABASE_URL=" + fmt.Sprintf(pg, "ledger_owner", "ledger"),
		"LEDGER_GRPC_ADDR=127.0.0.1:7001",
		"LEDGER_ADMIN_ADDR=127.0.0.1:7101",
		"LEDGER_TLS_CERT_FILE=" + filepath.Join(abs, "certs", "ledger.pem"),
		"LEDGER_TLS_KEY_FILE=" + filepath.Join(abs, "certs", "ledger-key.pem"),
		"LEDGER_GRPC_TARGET=localhost:7001",
		"LEDGER_TLS_SERVER_NAME=ledger",
		"",
		"IDENTITY_DATABASE_URL=" + fmt.Sprintf(pg, "identity_app", "identity"),
		"IDENTITY_OWNER_DATABASE_URL=" + fmt.Sprintf(pg, "identity_owner", "identity"),
		"IDENTITY_HTTP_ADDR=127.0.0.1:8002",
		"IDENTITY_GRPC_ADDR=127.0.0.1:7002",
		"IDENTITY_ADMIN_ADDR=127.0.0.1:7102",
		"IDENTITY_TLS_CERT_FILE=" + filepath.Join(abs, "certs", "identity.pem"),
		"IDENTITY_TLS_KEY_FILE=" + filepath.Join(abs, "certs", "identity-key.pem"),
		"IDENTITY_GRPC_TARGET=localhost:7002",
		"IDENTITY_TLS_SERVER_NAME=identity",
		"IDENTITY_TOKEN_SIGNING_KEY_FILE=" + filepath.Join(abs, "keys", "token-signing.pem"),
		"IDENTITY_BVN_HMAC_KEY=" + hmacKey,
		"IDENTITY_BVN_ENC_KEY=" + encKey,
		"IDENTITY_BVN_PROVIDER=simulator",
		"IDENTITY_KYC_TIER_ON_BVN_MATCH=2",
		"TOKEN_PUBLIC_KEY_FILE=" + filepath.Join(abs, "keys", "token-public.pem"),
		"",
		"LENDING_DATABASE_URL=" + fmt.Sprintf(pg, "lending_app", "lending"),
		"LENDING_OWNER_DATABASE_URL=" + fmt.Sprintf(pg, "lending_owner", "lending"),
		"LENDING_HTTP_ADDR=127.0.0.1:8003",
		"LENDING_ADMIN_ADDR=127.0.0.1:7103",
		"LENDING_TLS_CERT_FILE=" + filepath.Join(abs, "certs", "lending.pem"),
		"LENDING_TLS_KEY_FILE=" + filepath.Join(abs, "certs", "lending-key.pem"),
		"LENDING_BUREAU_PROVIDER=simulator",
		"LENDING_PAYOUT_PROVIDER=simulator",
		"LENDING_COLLECTION_PROVIDER=simulator",
		"",
		"REDIS_ADDR=localhost:56379",
		"",
		"PROVIDER_SIM_ADDR=127.0.0.1:8090",
		"PROVIDER_SIM_URL=http://127.0.0.1:8090",
		"PROVIDER_SIM_API_KEY=local-sim-api-key",
		"PROVIDER_SIM_CALLBACK_SECRET=local-sim-callback-secret",
		"PROVIDER_SIM_CALLBACK_URL=http://127.0.0.1:8003/v1/provider-webhooks/payouts",
		"PROVIDER_SIM_COLLECTION_WEBHOOK_URL=http://127.0.0.1:8003/v1/provider-webhooks/payments",
		"",
		"DEVTOOLS_TLS_CERT_FILE=" + filepath.Join(abs, "certs", "devtools.pem"),
		"DEVTOOLS_TLS_KEY_FILE=" + filepath.Join(abs, "certs", "devtools-key.pem"),
	}
	if err := os.WriteFile(filepath.Join(dir, "local.env"), []byte(strings.Join(env, "\n")+"\n"), 0o600); err != nil {
		return err
	}
	fmt.Println("wrote", filepath.Join(dir, "local.env"), "and development certificates (valid 7 days; re-run to renew)")
	return nil
}

func topics() error {
	brokers := strings.Split(envOr("KAFKA_BROKERS", "localhost:59092"), ",")
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	// Single partition and replication factor 1: a one-broker laptop cluster.
	// Production values (partitions, RF 3, min ISR 2) are set by
	// infrastructure as code, per the architecture plan.
	return kafkax.EnsureTopics(ctx, brokers, 1, 1, contract.TopicJournals, app.TopicLoans, "lending.collections.dlq")
}

func fund(customer, amount string) error {
	id, err := uuid.Parse(customer)
	if err != nil {
		return fmt.Errorf("customer id: %w", err)
	}
	minor, err := strconv.ParseInt(amount, 10, 64)
	if err != nil || minor <= 0 {
		return fmt.Errorf("amount_minor must be a positive integer")
	}
	l := config.FromEnv()
	tlsCfg, err := grpcx.ClientTLS(l.String("DEVTOOLS_TLS_CERT_FILE"), l.String("DEVTOOLS_TLS_KEY_FILE"), l.String("TLS_CA_FILE"), l.StringOr("LEDGER_TLS_SERVER_NAME", "ledger"))
	if lerr := l.Err(); lerr != nil {
		return lerr
	}
	if err != nil {
		return err
	}
	conn, err := grpcx.Dial(grpcx.ClientConfig{Target: l.String("LEDGER_GRPC_TARGET"), TLS: tlsCfg})
	if err != nil {
		return err
	}
	defer conn.Close()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	resp, err := ledgerv1.NewLedgerServiceClient(conn).PostJournal(ctx, &ledgerv1.PostJournalRequest{
		Ref:         &ledgerv1.PostingRef{OpType: "DEV_FUNDING", OpId: uuid.NewString(), OpStep: "POST"},
		JournalType: "DEV_FUNDING",
		Lines: []*ledgerv1.Line{
			{AccountCode: "SYS:DEV_FUNDING", Direction: ledgerv1.Direction_DIRECTION_DEBIT, Amount: &commonv1.Money{MinorUnits: minor, Currency: "NGN"}},
			{AccountCode: contract.CustomerDepositCode(id.String()), Direction: ledgerv1.Direction_DIRECTION_CREDIT, Amount: &commonv1.Money{MinorUnits: minor, Currency: "NGN"}},
		},
	})
	if err != nil {
		return err
	}
	fmt.Println("posted journal", resp.GetJournalId())
	return nil
}
